// footprint file for ergogen automatically generated by kicad-to-ergogen
// include it in ergogen/src/footprints/index.js using
//     require('path/to/this/file.js')
module.exports = {
    nets: {
      from: undefined,
      to: undefined
    },
    params: {
      class: 'D'
    },
    body: p => {
      return `
        (footprint "ComboDiode" (layer "F.Cu") (tedit 5B24D78E)  
        ${p.at /* parametric position */}
        (attr through_hole) 
        (fp_text reference "${p.ref}" (at 0 0 ${p.rot}) (layer "F.SilkS") ${p.ref_hide} (effects (font (size 1.27 1.27) (thickness 0.15))) (tstamp d3531ad3-ea7d-429d-956e-ff3da633d95c)) 
        (fp_text value "" (at 0 0 ${p.rot}) (layer "F.SilkS") hide (effects (font (size 1.27 1.27) (thickness 0.15))) (tstamp 3de3899f-ecd3-4a2a-a1ab-87cef4e94650)) 
        (fp_line (start 0.25 0.4) (end -0.35 0) (layer "B.SilkS") (width 0.1) (tstamp 0965facf-d28f-4f3e-92e5-6e21d166dbf1)) 
        (fp_line (start -0.75 0) (end -0.35 0) (layer "B.SilkS") (width 0.1) (tstamp 0a6c6964-517b-4ffa-8358-a6e43ec1666e)) 
        (fp_line (start 0.25 -0.4) (end 0.25 0.4) (layer "B.SilkS") (width 0.1) (tstamp 63fcfc59-7439-416e-96ce-38a112eb4939)) 
        (fp_line (start -0.35 0) (end 0.25 -0.4) (layer "B.SilkS") (width 0.1) (tstamp 6f13e8dd-8f95-4897-aa4a-7af39b71330f)) 
        (fp_line (start -0.35 0) (end -0.35 0.55) (layer "B.SilkS") (width 0.1) (tstamp cbc96328-cf32-4afa-9f80-62cf7d10af5b)) 
        (fp_line (start -0.35 0) (end -0.35 -0.55) (layer "B.SilkS") (width 0.1) (tstamp d0754a39-0cf1-4bbe-83a4-6155f2cbc878)) 
        (fp_line (start 0.25 0) (end 0.75 0) (layer "B.SilkS") (width 0.1) (tstamp de3a62ce-7926-4017-b32c-e08b5240df4f)) 
        (fp_line (start -0.35 0) (end -0.35 0.55) (layer "F.SilkS") (width 0.1) (tstamp 59501395-780b-47e4-8967-9f965674a799)) 
        (fp_line (start -0.35 0) (end -0.35 -0.55) (layer "F.SilkS") (width 0.1) (tstamp 711565b5-75c9-4d3f-bcee-afb8175cf923)) 
        (fp_line (start 0.25 0) (end 0.75 0) (layer "F.SilkS") (width 0.1) (tstamp bbc86d48-5ce4-4ddd-b79b-6c45ad7d510b)) 
        (fp_line (start 0.25 0.4) (end -0.35 0) (layer "F.SilkS") (width 0.1) (tstamp be38f05b-751e-404a-94cf-568c58838c13)) 
        (fp_line (start -0.35 0) (end 0.25 -0.4) (layer "F.SilkS") (width 0.1) (tstamp d9305b65-05ec-4b58-9e1d-12260ccab5b4)) 
        (fp_line (start -0.75 0) (end -0.35 0) (layer "F.SilkS") (width 0.1) (tstamp d9661e06-f322-4141-a260-e567444a0f5a)) 
        (fp_line (start 0.25 -0.4) (end 0.25 0.4) (layer "F.SilkS") (width 0.1) (tstamp f418e77d-5d63-4bf4-8e48-568fcb58ce44)) 

        (pad 1 thru_hole circle (at -1.65 0 ${p.rot}) (size 0.6 0.6) (drill 0.3) (layers *.Cu *.Mask) (tstamp 0719659f-0e4d-4bc3-90f2-cca9c1f2f3c2) ${p.net.to.str}) 
        (pad 1 smd rect (at -1.65 0 ${p.rot}) (size 0.9 1.2) (layers "B.Cu" "B.Paste" "B.Mask") (tstamp bb7e1885-8c5b-40e4-a514-27aa758ecfd2) ${p.net.to.str}) 
        (pad 1 smd rect (at -1.65 0 ${p.rot}) (size 0.9 1.2) (layers "F.Cu" "F.Paste" "F.Mask") (tstamp cf6c9828-d663-47f6-a4ca-8ec07a2d5311) ${p.net.to.str}) 
        (pad 2 smd rect (at 1.65 0 ${p.rot}) (size 0.9 1.2) (layers "F.Cu" "F.Paste" "F.Mask") (tstamp 118ed1ab-c2e9-4045-abaf-c084798b5aaf) ${p.net.from.str}) 
        (pad 2 smd rect (at 1.65 0 ${p.rot}) (size 0.9 1.2) (layers "B.Cu" "B.Paste" "B.Mask") (tstamp f49665ae-fbc7-4b7f-a9b5-8cfef2850911) ${p.net.from.str})
        (pad 2 thru_hole circle (at 1.65 0 ${p.rot}) (size 0.6 0.6) (drill 0.3) (layers *.Cu *.Mask) (tstamp 778a6e9b-8450-4751-9ce7-950e829a0e06) ${p.net.from.str}))
      `
    }
  }